services:
  standalone-firefox:
    image: selenium/standalone-firefox:4.28.1-20250123
    shm_size: 2gb
    ports:
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443